# Site settings
title: Containium
tagline: "Dev & Ops friendly microservices in Clojure"
email: info@containium.org
description: > # this means to ignore newlines until "baseurl:"
  Opinionated libraries and Systems for building isolated applications (Containium)
  and fully custom Clojure Application Servers (Reactor).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://containium.org" # the base hostname & protocol for your site
twitter_username: containium
github_username:  containium

# Build settings
markdown: kramdown

kramdown:
  input: GFM